import React from 'react'

const Home = () => {
    return (
        <div>
            <center>
                <h2>Welcome to Home Page</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime recusandae nostrum tempora, sapiente consectetur qui ab hic incidunt totam labore modi dolores molestias commodi ea laborum aut tenetur excepturi sit, ullam aliquid ex! Debitis sed molestias doloremque? Voluptatibus reprehenderit sequi temporibus inventore laboriosam quasi cum nostrum veritatis laudantium cumque corporis commodi quos culpa cupiditate id impedit aperiam qui a atque soluta ad, iste ipsam. Commodi unde quibusdam maxime libero labore perferendis reprehenderit deserunt corporis ea quos, laborum voluptate aliquid dolor suscipit excepturi? At ex quibusdam, fugiat, eligendi ad pariatur cupiditate non repellat perspiciatis similique veniam architecto nesciunt ipsa debitis totam.</p>


            </center>
        </div>
    )
}

export default Home
